# Plate Validators Configuration for ModernSatsuma

dotnet:
  # Layer and company naming
  layer_name: "Plate"
  company_prefix: "GiantCroissant"
  project_name: "ModernSatsuma"

  # Namespace configuration
  skip_intermediate_dirs: false

  # Dependency rules - no external dependencies in this standalone library
  dependency_rules:
    "Plate.ModernSatsuma":
      can_reference: []
      cannot_reference: []

  # Blacklist - forbidden namespace patterns
  blacklist:
    - "Satsuma"  # Old namespace, migrated to Plate.ModernSatsuma

  # Whitelist - allowed namespace patterns
  whitelist:
    - "Plate"
    - "System"
    - "Microsoft"

  # Package ID validation
  enforce_package_id_convention: true
  packable_only: true

  # .csproj validation
  required_properties:
    - "TargetFramework"
    - "LangVersion"

  allow_cpm: true  # Allow Central Package Management

common:
  # TODO format validation
  todo_format: "TODO(author): description"

  # File naming convention
  file_naming: "PascalCase"

  # Exclude patterns
  exclude_patterns:
    - "*.Designer.cs"
    - "*.g.cs"
    - "*.g.i.cs"
    - "*.min.*"
    - "*.generated.*"
    - "**/obj/**"
    - "**/bin/**"
    - "**/node_modules/**"
    - "**/.git/**"
    - "**/build/**"
